### ISSUE TITLE
Can't find template

### ISSUE THREAD

**Issue by flaprogrammer** [jsvalley/ng2-datetime-picker#1]
I didn't configure **systemjs.config.js**, cause I used angular2-webpack-starter.
So I imported module with 
`
import {DateTimePickerDirective} from "ng2-datetime-picker";`

Everything is ok, but when I focus on input, it throws exception

_http://localhost:3000/datetime-picker.html 404 (Not Found)
Unhandled Promise rejection: Failed to load /datetime-picker.html ; Zone: angular ; Task: Promise.then ; Value: Failed to load /datetime-picker.html_

And datepicker doesn't shows
Maybe I'm doing something wrong?

**Comment by allenhwkim** [comment]
I do not know about webpack, but you need to tell the system when you import from 'ng2-datetime-packer', tell it where to search.

Normally it's from node_modules/ng2-datetime-picker, but if not, then it must be somewhere

and it should not look for http://localhost:3000/datetime-picker.html, and it should look for something like node_modules/ng2-datetime-picker/dist/datetime-picker.html

I would really appreciate someone who knows about webpack can help me and you.

**Comment by flaprogrammer** [comment]
Yes, inline templating solved this problem, thanks =)
But now I see new issue, when I click to picker, it closes. So I can't change the month on calendar.
And in the demo link http://embed.plnkr.co/32syXF/ it's not the picker, so I can't know how it should work

**Comment by allenhwkim** [comment]
Do you use the recent version of ng2-datetime-picker? The earlier version had that issue.

**Comment by allenhwkim** [comment]
This is a new plunker, http://plnkr.co/edit/lbNRAh?p=preview

**Comment by flaprogrammer** [comment]
Yes, I use 0.1.8 of ng2-datetime-picker version, Angular version rc.1
OS X El Capitan, Chrome 51

**Comment by allenhwkim** [comment]
Sorry, I realized that it's a bug that we currently have. Sorry about that. I will make a fix soon.

**Comment by allenhwkim** [comment]
This has been fixed and released with 0.1.9. Please verify the fix is correct

**Comment by flaprogrammer** [comment]
Now it's ok! Thank you! 
Could you also inline your css and html?

**Comment by allenhwkim** [comment]
inline css and html is done using [ng2-inline-template](https://github.com/jsvalley/ng2-inine-template)

**Comment by flaprogrammer** [comment]
You're great! Thank you
