### ISSUE TITLE
Selection of year and month

### ISSUE THREAD

**Issue by kjwm** [jsvalley/ng2-datetime-picker#3]
How can i select a specific year or month ?

**Comment by allenhwkim** [comment]
just specify year and month. e.g. year="1969" month="12"

**Comment by kjwm** [comment]
Thank you but I meant something like this

![datepicker](https://cloud.githubusercontent.com/assets/5208669/16442254/c280fbd0-3dd9-11e6-94ea-43e597230f26.png)

**Comment by allenhwkim** [comment]
This has not been planned. If more user request this feature, I will reopen this feature.
