### ISSUE TITLE
Exception in IE 11

### ISSUE THREAD

**Issue by zeljko-bulatovic** [jsvalley/ng2-datetime-picker#4]
Hello,

Thanks for this great component, but there is exception when control is opened in IE 11.

Exception stacktrace:
EXCEPTION: Error in ../ng2-datetime-picker/dist/datetime-picker.component.js class anonymous_token_72_ - inline template:5:11
ORIGINAL EXCEPTION: TypeError: Unable to get property 'fullName' of undefined or null reference

This exception occurs, when you want to change time.

Usage:
<input [(ngModel)]="timeStart" datetime-picker class="form-control" />

In chrome and firefox is working great!

Any help?

Thanks!

**Comment by allenhwkim** [comment]
Thanks for using this. Interesting bug, I will take a look into it.

**Comment by allenhwkim** [comment]
This has been fixed with 0.2.1 release.
