### ISSUE TITLE
1 day off

### ISSUE THREAD

**Issue by spalt** [jsvalley/ng2-datetime-picker#6]
hi again!
it seems when you select a date on the calendar, and the calendar closes, when you open it again, it defaults to 1 day before the currently selected day.  i.e. in your plnkr, the date defaults to 2015-01-01 but when you click it it shows 2014-12-31.
thanks!

**Comment by allenhwkim** [comment]
This is a serious bug, I will make a fix soon.

**Comment by allenhwkim** [comment]
Thanks for reporting this bug, I made a fix and released a new version 0.3.1. please do `npm update ng2-datetime-picker`

**Comment by spalt** [comment]
thanks!
